### ISSUE TITLE
ssl::stream writes inefficient when buffer sequences have length > 1

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/asio#100]
The write algorithms for `ssl::stream` end up performing a separate call to the underlying stream's `write_some` or `async_write_some` function for each individual buffer in a buffer sequence. This has performance implications when the buffer sequence has more than one element. These are related:

https://stackoverflow.com/questions/38198638/openssl-ssl-write-from-multiple-buffers-ssl-writev
https://stackoverflow.com/questions/50026167/performance-drop-on-port-from-beast-1-0-0-b66-to-boost-1-67-0-beast
https://github.com/boostorg/beast/issues/1108

**Comment by badfd** [comment]
I have first-hand experience with the excessive number of system calls caused by `asio::ssl::stream`.

For a fixed number of app-level HTTPS messages, here is the `strace -cf` output for both with and without `flat_stream` ...

First, a count of the calls to `sendmsg` without `flat_stream` (865589):
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 94.07 2754.818654        1449   1901618    399724 futex
  3.31   96.798247      649653       149           nanosleep
  1.64   47.988316          55    865589           sendmsg
  0.36   10.523860         170     61970           recvmsg
  0.21    6.217944          50    123614           timer_settime
  0.21    6.089656          49    123614           timer_create
  0.21    6.084648          49    123614           timer_delete
  o o o
```

And here is the count with `flat_stream` (62573):
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 95.17 1227.002496         883   1390306    212175 futex
  3.19   41.115119      348433       118           nanosleep
  0.76    9.787660         156     62672           recvmsg
  0.24    3.078478          25    125018           timer_settime
  0.24    3.032991          24    125018           timer_create
  0.23    3.014875          24    125018           timer_delete
  0.17    2.140766          34     62573           sendmsg
  o o o
```
As you can see, for the `flat_stream` case there's essentially a **1**-to-**1** ratio of calls to `sendmsg` vs calls to `recvmsg`. Conversely, for the non-`flat_stream` case that same ratio is essentially a **14**-to-**1**.

**Comment by TheStormN** [comment]
Hey all, is this issue still present in pure ASIO? I see that `ssl::stream` is now movable, but not sure if the scatter/gather performance is fixed?

**Comment by vinniefalco** [comment]
I do believe this was fixed in Asio, here: https://github.com/boostorg/asio/commit/2f327be5fed7b19d8c027fbcbba3a8b883edfa16#diff-c71ff1a2ef349841e0fa204d7e13400aab4677ac8853d8b21081105dbb6f7f18
