### ISSUE TITLE
Is this comment correct? [service vs owning context lifetime]

### ISSUE THREAD

**Issue by traceon** [boostorg/asio#187]
https://github.com/boostorg/asio/blob/fbe86d86b1ac53e40444e5af03ca4a6c74c33bda/include/boost/asio/execution_context.hpp#L72-L74

The paragraph above doesn't seem correct, since the `execution_context::destroy()` is a protected member function, meaning any custom execution context that derives from `execution_contex` will be able to call it outside of its d-tor, or I am missing something?

**Comment by djarek** [comment]
It has to be a protected member so that the derived class can call `destroy()` in its own destructor. This is necessary, e.g. when you install a service that refers back to the derived context object and has to access its members in `shutdown()` or its destructor. 

In general, just because you can call it in any context, does not mean you should :).

**Comment by traceon** [comment]
I see, so together with this, that makes sense and is not conflicting:
https://github.com/boostorg/asio/blob/fbe86d86b1ac53e40444e5af03ca4a6c74c33bda/include/boost/asio/execution_context.hpp#L86-L88

but, are objects of derived classes allowed to call `destroy()` or `shutdown()` **before** they are destructed (to sort of erase the set of the services, for example)?

**Comment by djarek** [comment]
I believe they are allowed to do that, but the ExecutionContext might not be in a usable state (e.g. adding a service might be UB at that point), so definitely don't try reseting a context with them (unless there's a guarantee of that not being UB somewhere).
