### ISSUE TITLE
1.70 change with io_context/strand isn't reflected in boost::process

### ISSUE THREAD

**Issue by complexmath** [boostorg/asio#251]
In 1.69, strands were initialized from a socket via:
```
boost::asio::tcp::socket sock;
boost::asio::io_context::strand s(sock.get_io_context());
```
get_io_context() was dropped in 1.70, with the new approach being:
```
boost::asio::tcp::socket sock;
boost::asio::strand<boost::asio::executor> s(boost::asio::make_strand(socket.get_executor()));
```
However, it appears other Boost packages weren't updated to reflect this change. `async_pipe` in boost::process is still initialized via an `io_context`, for example. Is there a correct way to obtain an `io_context` from a socket instance?

**Comment by djarek** [comment]
If you're dealing with an `executor`-aware facility you should just initialize the socket with the executor you want to use (works fine for regular callbacks, more care has to be taken with specialized CompletionTokens):
```
asio::io_context ioc;
asio::tcp::socket sock{asio::make_strand{ioc.get_executor()}};
```
if you want to use the strand for another I/O object, e.g. a timer, you can just use the executor directly:
```
asio::steady_timer timer{sock.get_executor()};
```

Note that `get_io_context()` and `get_io_service()` have been deprecated for a long time now (since 1.66).

Another thing worth keeping in mind is that by default, I/O objects in ASIO use type-erasure (`asio::executor`). If you want to avoid it and use an executor type directly, you'll need to use the `basic_` templates:
```
asio::basic_stream_socket<asio::ip::tcp, asio::io_context::executor_type> socket{ioc};
asio::io_context& ctx = socket.get_executor().context(); // This is only guaranteed to work for asio::io_context::executor_type
```

As to why boost::process didn't update - I don't know, you should ask there :)

**Comment by complexmath** [comment]
Yeah that just means having a statically available io_context, which I'd avoided thus far. It would address the boost::process issue as well though. I filed this mostly because I was surprised that get_io_context() was removed when there were other Boost modules that haven't updated things yet. Suppose I'll file a ticket on boost::process in hopes that they'll sort things out on their side and then decide if I'm going to hold on 1.69 or expose io_context.
